name: main CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm install

  publish-image:

    runs-on: ubuntu-latest
    steps:
    - name: Build docker image
    - uses: actions/checkout@v3
    - run: docker build . -t ritcheyy/petadopt-api

    - name: Publish docker image
    - uses: actions/checkout@v3
    - run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
    - run: docker push ritcheyy/petadopt-api
